export const CommitteeRequestsData = [
  {
    id: 1,
    requisition: "BOB/HRM/REC/ADVT/2025/06",
    position: "Deputy Manager : ONDC",
    panelType: "Interview",
    panelMembers: ["Veeresh V", "Vijay V", "Naresh P"],
    startDate: "05-01-2026",
    endDate: "05-01-2026",
    status: "Approved",
  },
  {
    id: 2,
    requisition: "BOB/HRM/REC/ADVT/2025/06",
    position: "Product - Account Aggregator",
    panelType: "Compensation",
    panelMembers: ["Sathvik P", "Satish J", "Barat T"],
    startDate: "12-01-2026",
    endDate: "21-01-2026",
    status: "Pending",
  },
  {
    id: 3,
    requisition: "BOB/HRM/REC/ADVT/2025/06",
    position: "Product - ONDC",
    panelType: "Screening",
    panelMembers: ["Saibaba B", "Prabhakar K", "Vijay"],
    startDate: "15-01-2026",
    endDate: "27-01-2026",
    status: "Pending",
  },
  {
    id: 4,
    requisition: "BOB/HRM/REC/ADVT/2025/07",
    position: "Senior Developer : Tech",
    panelType: "Interview",
    panelMembers: ["Ramesh K", "Suresh M", "Ganesh P"],
    startDate: "10-01-2026",
    endDate: "15-01-2026",
    status: "Approved",
  },
  {
    id: 5,
    requisition: "BOB/HRM/REC/ADVT/2025/08",
    position: "Business Analyst : Operations",
    panelType: "Screening",
    panelMembers: ["Priya S", "Kavya R", "Divya M"],
    startDate: "18-01-2026",
    endDate: "25-01-2026",
    status: "Rejected",
  },
];
