export const ExtensionsRequestsData = [
  {
    id: 1,
    name: "Sarah Johnson",
    initials: "SJ",
    regNo: "961325467",
    requestDate: "08-06-2025",
    requestTime: "2:30 PM",
    requisition: "BOB/HRM/REC/ADVT/2025/06",
    position: "Deputy Manager : ONDC",
    requestType: "Extension",
    status: "Approved",
  },
  {
    id: 2,
    name: "Michael Chen",
    initials: "MC",
    regNo: "961325857",
    requestDate: "12-07-2025",
    requestTime: "2:30 PM",
    requisition: "BOB/HRM/REC/ADVT/2025/06",
    position: "Product - Account Aggregator",
    requestType: "Extension",
    status: "Pending",
  },
  {
    id: 3,
    name: "Emily Rodriguez",
    initials: "ER",
    regNo: "961524789",
    requestDate: "16-08-2025",
    requestTime: "2:30 PM",
    requisition: "BOB/HRM/REC/ADVT/2025/06",
    position: "Product - ONDC",
    requestType: "Extension",
    status: "Pending",
  },
  {
    id: 4,
    name: "Ramesh Kumar",
    initials: "RK",
    regNo: "962145789",
    requestDate: "10-01-2026",
    requestTime: "11:15 AM",
    requisition: "BOB/HRM/REC/ADVT/2025/07",
    position: "Senior Developer : Tech",
    requestType: "Extension",
    status: "Approved",
  },
  {
    id: 5,
    name: "Priya Sharma",
    initials: "PS",
    regNo: "963254178",
    requestDate: "18-01-2026",
    requestTime: "4:00 PM",
    requisition: "BOB/HRM/REC/ADVT/2025/08",
    position: "Business Analyst : Operations",
    requestType: "Extension",
    status: "Rejected",
  },
];
